print('-='*30)
times = ('Athletico-Pr', 'Bahia', 'Flamengo', 'Botafogo', 'São Paulo', 'Cruzeiro', 'Atletico-MG', 'Bargantino', 'Palmeiras', 'Internacional', 'Fortaleza', 'Gremio', 'Vaso da Gama', 'Criciuma', 'Juventude', 'Corinthians', 'Fluminense', 'EC Vitoria', 'Atletico-GO', 'Cuiaba')
print(f'Lista do Brasileirao = {times}')
print('-='*30)
print(f'Os 5 primeiros são {times[0:5]}')
print('-='*30)
print(f'Os 4 últimos são {times[16:]}')
print('-='*30)
print(f'Times em ordem alfabetica {sorted(times)}')
print('-='*30)
print(f'O Corinthians esta na {len('Corinthians')}° posição')
